### ISSUE TITLE
⚡ Standardization of rep

### ISSUE THREAD

**Issue by luxonauta** [dracula/protonmail#1]
Hi @Blisterexe and @breatfr, we need to adjust a few things first to move forward, ok? ✨

We need a separate `.md` with installation instructions to show the theme on the site.

I ask for these changes to standardize with the other repositories [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would like to contribute too! 😁

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by Blisterexe** [comment]
Done! Thank you for telling me, and tell me if i did something wrong!
